# jedi
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
hook_source = '''
  let g:jedi#popup_select_first = 0
  let g:jedi#popup_on_dot = 0
  let g:jedi#use_tabs_not_buffers = 1
  let g:jedi#auto_vim_configuration = 1
  autocmd FileType python setlocal completeopt=menuone,longest
'''

[[plugins]]
repo = 'ervandew/supertab'
on_ft = 'python'
hook_add = '''
  let g:SuperTabDefaultCompletionType = "<c-n>"
'''
